### ISSUE TITLE
レスポンスが`'Content-Type': 'image/jpeg'`のデータにも対応させる

### ISSUE THREAD

**Issue by tamago324** [tamago324/PyTwitcasting#1]
[Get Live Thumbnail Image](http://apiv2-doc.twitcasting.tv/#get-live-thumbnail-image)で取得できるデータが`'Content-Type': 'image/jpeg'`となっているため、対応できるように`PyTwitcasting._get()`を改修する

**Comment by tamago324** [comment]
エラー内容

```sh
Loading .env environment variables…
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    twitcas.get_live_thumbnail_image('tamago324_pad')
  File "/Users/tamago324/Programing/programs/Python/02_twitcastingApps/06_PyTwitcasting/pytwitcasting.py", line 250, in get_live_thumbnail_image
    return self._get(f'/users/{user_id}/live/thumbnail')
  File "/Users/tamago324/Programing/programs/Python/02_twitcastingApps/06_PyTwitcasting/pytwitcasting.py", line 194, in _get
    return self._internal_call('GET', url, payload, kwargs)
  File "/Users/tamago324/Programing/programs/Python/02_twitcastingApps/06_PyTwitcasting/pytwitcasting.py", line 181, in _internal_call
    return r.json()
  File "/Users/tamago324/.local/share/virtualenvs/06_PyTwitcasting-KB_jrYNk/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

今まで実装していたメソッドで取得していたデータのレスポンスを見てみると`'Content-Type': 'application/json;charset=utf-8'`となっていた

JSON形式だから、`response.json()`で変換できたってことか

Content-Typeが`image/jpeg`か`image/png`ではなかったらJSONに変換すればいいのかな

**Comment by tamago324** [comment]
a088520e0a1afd2b3dc4da8722b6d37aa6cb71fa で修正した

でも、`r.content`でいいのかは不明

**Comment by tamago324** [comment]
[Quickstart — Requests 2.18.4 documentation](http://docs.python-requests.org/en/master/user/quickstart/#raw-response-content)

Rawじゃない！？って思った

**Comment by tamago324** [comment]
画像で保存してみるといいかも？

**Comment by tamago324** [comment]
[Developer Interface — Requests 2.18.4 documentation](http://docs.python-requests.org/en/master/api/#requests.Response)によると`response.content`はbytesのデータが取得できる

[requestsを使った画像のダウンロード - Qiita](https://qiita.com/donksite/items/21852b2baa94c94ffcbe)を参考に画像で保存してみよう

**Comment by tamago324** [comment]
bytesデータと拡張子を返すようにした

**Comment by tamago324** [comment]
サムネイルを取得して画像で保存するサンプル

```python
def save_image_test(user_id):
    token = os.environ['ACCESS_TOKEN']
    twitcas = Twitcasting(token)

    thumbnail = twitcas.get_live_thumbnail_image(user_id)
    save_image(thumbnail['bytes_data'], f"cas.{thumbnail['file_ext']}")

def save_image(img_bytes, file_name):
    dir_name = os.path.dirname(os.path.abspath(__file__))
    with open(f'{dir_name}/{file_name}', 'wb') as f:
        f.write(img_bytes)

if __name__ == '__main__':
    save_image_test('tamago324_pad')
```
