### ISSUE TITLE
Read the Docsで正しく表示されない

### ISSUE THREAD

**Issue by tamago324** [tamago324/PyTwitcasting#30]
https://readthedocs.org/projects/pytwitcasting/builds/7535244/

```
Running Sphinx v1.7.6

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 163, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
ConfigError: There is a syntax error in your configuration file: invalid syntax (conf.py, line 186)

Configuration error:
There is a syntax error in your configuration file: invalid syntax (conf.py, line 186)
```

**Comment by tamago324** [comment]
https://github.com/tamago324/PyTwitcasting/blob/f3aeee8c0615cc4ac48b171cd49eea87ade346c0/docs/conf.py#L186

ここのせいなのかな

てか、Python2.7でビルドしてるのが気になる。。。

ビルドのバージョンを指定できるっぽい

[Read the Docs YAML Config — Read the Docs 1.0 documentation](https://docs.readthedocs.io/en/latest/yaml-config.html#python-version)

`readthedocs.yml`をプロジェクトのルートに作成してみた

```yaml
# readthedocs.yml
python:
   version: 3.5
```

そしたら、[結果が変わった](https://readthedocs.org/projects/pytwitcasting/builds/7535483/)

**Comment by tamago324** [comment]
```
Running Sphinx v1.7.6

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 141, in execfile_
    code = compile(source, filepath_enc, 'exec')
  File "conf.py", line 186
    for fileName in sorted(glob.glob(f'../{PROJECT_NAME}/*.py'))
                                                             ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 73, in convert_with_2to3
    tree = refactoring_tool.refactor_string(source, 'conf.py')
  File "/usr/lib/python3.5/lib2to3/refactor.py", line 380, in refactor_string
    name, err.__class__.__name__, err)
  File "/usr/lib/python3.5/lib2to3/refactor.py", line 377, in refactor_string
    tree = self.driver.parse_string(data)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=3, value="'../{PROJECT_NAME}/*.py'", context=('', (186, 38))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 146, in execfile_
    source = convert_with_2to3(filepath)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/util/pycompat.py", line 78, in convert_with_2to3
    raise SyntaxError(err.msg, (filepath, lineno, offset, err.value))
  File "conf.py", line 186
    '../{PROJECT_NAME}/*.py'
                           ^
SyntaxError: bad input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/application.py", line 163, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pytwitcasting/envs/latest/lib/python3.5/site-packages/sphinx/config.py", line 163, in __init__
    raise ConfigError(CONFIG_SYNTAX_ERROR % err)
sphinx.errors.ConfigError: There is a syntax error in your configuration file: bad input (conf.py, line 186)
Did you change the syntax from 2.x to 3.x?

Configuration error:
There is a syntax error in your configuration file: bad input (conf.py, line 186)
Did you change the syntax from 2.x to 3.x?
```

**Comment by tamago324** [comment]
あ、、、f-stringってPython3.6からなのか...

[Python 3.6の新機能f-strings（フォーマット文字列リテラル）について - Read -> Blog](http://codom.hatenablog.com/entry/2016/12/27/000000)

**Comment by tamago324** [comment]
conf.pyは2.7でも動くように書いたほうがいいってことか
